PASSING_PROBLEMS = [
    "balanced_field",
    "ballistic_spacecraft",
    "battery_multibranch",
    "brachistochrone",
    "brachistochrone_tandem_phases",
    "breakwell",
    "bryson_denham",
    "cannonball_implicit_duration",
    "cart_pole",
    "commercial_aircraft",
    "double_integrator",
    "finite_burn_orbit_raise",
    "flying_robot",
    "goddard_rocket",
    "hull",
    "hypersensitive",
    "length_constrained_brachistochrone",
    "low_thrust_spiral",
    "min_time_climb",
    "moon_landing",
    "mountain_car",
    "multi_phase_cannonball",
    "robot_arm",
    "shuttle_reentry_constrained",
    "shuttle_reentry_unconstrained",
    "ssto_earth",
    "ssto_linear_tangent",
    "vanderpol",
    "water_rocket_height",
    "water_rocket_range",
]

DISABLED_PROBLEMS = [
    "racecar",
]
