cc_test(
    name = "simple_nlp",
    size = "small",
    srcs = ["test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@sip//sip",
        "@sip_qdldl//sip_qdldl",
        "@qdldl//:qdldl",
    ],
)
